# Generated by Django 5.2.7 on 2025-11-02 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('cold', 'Below -10°C'), ('cool', '-10°C to +10°C'), ('warm', 'Above +10°C')], max_length=10)),
                ('items', models.TextField(help_text='Comma-separated list of clothing items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_choices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['group'],
                'unique_together': {('user', 'group')},
            },
        ),
    ]
