# Generated by Django 5.2.7 on 2025-11-02 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_clotheschoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of clothing item', max_length=100)),
                ('temperature_group', models.CharField(choices=[('cold', 'Below -10°C'), ('cool', '-10°C to +10°C'), ('warm', 'Above +10°C')], max_length=10)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clothing Item',
                'verbose_name_plural': 'Clothing Items',
                'ordering': ['temperature_group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserClothingChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_items', models.ManyToManyField(related_name='chosen_by_users', to='weather.clothingitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_choices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Clothing Choice',
                'verbose_name_plural': 'User Clothing Choices',
            },
        ),
        migrations.DeleteModel(
            name='ClothesChoice',
        ),
    ]
