# Generated by Django 5.2.6 on 2025-11-03 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
