# Generated by Django 5.2.6 on 2025-12-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_alter_like_unique_together_clothes_searchhistory'),
    ]

    operations = [
    ]
